#!/usr/bin/env ruby

USERNAME = "root"
HOSTNAME = "proxima.andreicek.lan"

def connection
	return "ssh " + USERNAME + "@" + HOSTNAME
end

def list
	esxi_Cmd = "vim-cmd vmsvc/getallvms"
	output = `#{connection() + " " + esxi_Cmd}`
	puts output
end

def status
	esxi_Cmd = "vim-cmd vmsvc/power.getstate"
	vm_Id = ARGV[1]
	output = `#{connection() + " " + esxi_Cmd + " " + vm_Id}`
	puts output
end

def VmOn
	esxi_Cmd = "vim-cmd vmsvc/power.on"
	vm_Id = ARGV[1]
	output = `#{connection() + " " + esxi_Cmd + " " + vm_Id}`
	puts output
end

def VmOff
	esxi_Cmd = "vim-cmd vmsvc/power.off"
	vm_Id = ARGV[1]
	output = `#{connection() + " " + esxi_Cmd + " " + vm_Id}`
	puts output
end

def menu
	choice = ARGV[0]
	if (choice == "list")
		list()
	elsif (choice == "status")
		status()
	elsif (choice == "on")
		VmOn()
	elsif (choice == "off")
		VmOff()
	elsif (choice == "restart")
		VmOff()
		sleep 5
		VmOn()
		status()
	#else
	#	help
	end
end

menu